  
language: ruby
rvm:
  - 2.7.1
script: "bundle exec jekyll build -d docs --config _config-dev.yml"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
